#!/bin/bash -e

#SBATCH --job-name ASMQC
#SBATCH --time=7-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --output pfr_assemblyqc.stdout
#SBATCH --error pfr_assemblyqc.stderr
#SBATCH --mem=4G

ml unload perl
ml apptainer/1.1
ml nextflow/23.04.4

export TMPDIR="/workspace/$USER/tmp"
export APPTAINER_BINDPATH="$APPTAINER_BINDPATH,$TMPDIR:$TMPDIR,$TMPDIR:/tmp"

nextflow \
    main.nf \
    -c pfr/profile.config \
    -profile pfr,apptainer \
    -resume \
    --params-file pfr/params.json
