name: "haphic_refsort"
description: A python script to order and orient whole scaffolds according to a
    reference genome.
keywords:
    - sort
    - order
    - orient
    - fasta
    - genomics
tools:
    - "haphic":
          description: "A fast, reference-independent, allele-aware scaffolding tool based
              on Hi-C data"
          homepage: "https://github.com/zengxiaofei/HapHiC"
          documentation: "https://github.com/zengxiaofei/HapHiC"
          tool_dev_url: "https://github.com/zengxiaofei/HapHiC"
          doi: "10.1038/s41477-024-01755-3"
          licence:
              - "BSD-3-Clause"
          identifier: ""
input:
    - - meta:
            type: map
            description: |
                Groovy Map containing sample information
                e.g. `[ id:'sample1' ]`
      - agp:
            type: file
            description: Query AGP
            pattern: "*.{agp}"
            ontologies: []
    - paf:
          type: file
          description: Alignment PAF
          pattern: "*.{paf}"
          ontologies: []
    - fasta:
          type: file
          description: Query Fasta
          pattern: "*.{fasta}"
          ontologies: []
    - ref_order:
          type: string
          description: Order of reference chromosomes
output:
    agp:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.agp":
                type: file
                description: Output AGP
                pattern: "*.{agp}"
                ontologies: []
    fasta:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.fasta":
                type: file
                description: Output query Fasta
                pattern: "*.{fasta}"
                ontologies: []
    versions_haphic:
        - versions.yml:
              type: file
              description: File containing software versions
              pattern: "versions.yml"
              ontologies:
                  - edam: http://edamontology.org/format_3750
topics:
    versions:
        - versions.yml:
              type: file
              description: File containing software versions
              pattern: "versions.yml"
              ontologies:
                  - edam: http://edamontology.org/format_3750
authors:
    - "@GallVp"
maintainers:
    - "@GallVp"
