name: "custom_yahsjuicerpre2tracks"
description: Converts a liftover AGP from YaHS to assembly, bedpe and bed files
keywords:
    - genomics
    - assembly
    - bedpe
    - biopython
    - custom
    - utility
tools:
    - "python":
          description: |
              Python is a programming language that lets you work quickly
              and integrate systems more effectively
          homepage: "https://www.python.org"
          documentation: "https://docs.python.org/3/"
          tool_dev_url: "https://github.com/python/cpython"
          licence:
              - "MIT"
          identifier: ""
input:
    - - meta:
            type: map
            description: |
                Groovy Map containing sample information
                e.g. `[ id:'sample1' ]`
      - liftover_agp:
            type: file
            description: Liftover AGP from YaHS
            ontologies: []
    - scale:
          type: file
          description: Scale text file
          ontologies: []
output:
    assembly:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.assembly":
                type: file
                description: Assembly file
                ontologies: []
    bedpe:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.bedpe":
                type: file
                description: BEDPE file
                ontologies: []
    bed:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.bed":
                type: file
                description: BED file
                ontologies: []
    versions_python:
        - versions.yml:
              type: file
              description: File containing software versions
              pattern: "versions.yml"
              ontologies:
                  - edam: http://edamontology.org/format_3750
topics:
    versions:
        - versions.yml:
              type: file
              description: File containing software versions
              pattern: "versions.yml"
              ontologies:
                  - edam: http://edamontology.org/format_3750
authors:
    - "@GallVp"
maintainers:
    - "@GallVp"
