name: "hictk_zoomify"
description: Zoomify hic files to add more resolutions
keywords:
    - genomics
    - hic
    - 4dn
    - pairs
tools:
    - "hictk":
          description: "Blazing fast toolkit to work with .hic and .cool files"
          homepage: "https://github.com/paulsengroup/hictk#readme"
          documentation: "https://github.com/paulsengroup/hictk#readme"
          tool_dev_url: "https://github.com/paulsengroup/hictk"
          doi: "10.1093/bioinformatics/btae408"
          licence:
              - "MIT"
          identifier: biotools:hictk
input:
    - - meta:
            type: map
            description: |
                Groovy Map containing sample information
                e.g. `[ id:'sample1' ]`
      - hic:
            type: file
            description: Input hic
            ontologies: []
output:
    hic:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.hic":
                type: file
                description: Output hic file
                ontologies: []
    versions_hictk:
        - - ${task.process}:
                type: string
                description: The name of the process
          - hictk:
                type: string
                description: The name of the tool
          - hictk --version:
                type: eval
                description: The expression to obtain the version of the tool
topics:
    versions:
        - - ${task.process}:
                type: string
                description: The name of the process
          - hictk:
                type: string
                description: The name of the tool
          - hictk --version:
                type: eval
                description: The expression to obtain the version of the tool
authors:
    - "@GallVp"
maintainers:
    - "@GallVp"
