name: "yahs_juicerpre"
description: Generate files compatible with Juicebox toolset
keywords:
    - genomics
    - hic
    - bam
    - juicer
tools:
    - "yahs":
          description: "YaHS, yet another Hi-C scaffolding tool."
          homepage: "https://github.com/c-zhou/yahs"
          documentation: "https://github.com/c-zhou/yahs"
          tool_dev_url: "https://github.com/c-zhou/yahs"
          doi: "10.1093/bioinformatics/btac808"
          licence:
              - "MIT"
          identifier: biotools:yahs
input:
    - - meta:
            type: map
            description: |
                Groovy Map containing sample information
                e.g. `[ id:'sample1' ]`
      - bam_or_bin:
            type: file
            description: BAM or BIN file
            pattern: "*.{bam,bin}"
            ontologies:
                - edam: "http://edamontology.org/format_2572"
                - edam: "http://edamontology.org/format_2573"
                - edam: "http://edamontology.org/format_3462"
    - agp:
          type: file
          description: AGP file
          pattern: "*.agp"
          ontologies: []
    - fai:
          type: file
          description: FAI file
          pattern: "*.fai"
          ontologies: []
output:
    txt:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.txt":
                type: file
                description: Links TSV file
                pattern: "*.txt"
                ontologies: []
    assembly:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.assembly":
                type: file
                description: Assembly file
                pattern: "*.assembly"
                ontologies: []
    assembly_agp:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.assembly.agp":
                type: file
                description: Assembly AGP file
                pattern: "*.assembly.agp"
                ontologies: []
    liftover_agp:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.liftover.agp":
                type: file
                description: Liftover AGP file
                pattern: "*.liftover.agp"
                ontologies: []
    sizes:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.sizes":
                type: file
                description: Sizes file for the assembly mode
                pattern: "*.sizes"
                ontologies: []
    scale:
        - - meta:
                type: map
                description: |
                    Groovy Map containing sample information
                    e.g. `[ id:'sample1' ]`
          - "*.scale":
                type: file
                description: The scale by which the assembly has been shrunk
                ontologies: []
    versions_yahs:
        - - ${task.process}:
                type: string
                description: The name of the process
          - yahs:
                type: string
                description: The name of the tool
          - yahs --version:
                type: eval
                description: The expression to obtain the version of the tool
topics:
    versions:
        - - ${task.process}:
                type: string
                description: The name of the process
          - yahs:
                type: string
                description: The name of the tool
          - yahs --version:
                type: eval
                description: The expression to obtain the version of the tool
authors:
    - "@GallVp"
maintainers:
    - "@GallVp"
